name: TorchMarker
channels:
  - conda-forge
  - defaults
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.9.9
  - colorama=0.4.6
  - comm=0.2.3
  - debugpy=1.8.17
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libffi=3.4.4
  - libsodium=1.0.20
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.5.3
  - packaging=25.0
  - parso=0.8.5
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - psutil=7.1.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.18
  - python-dateutil=2.9.0.post0
  - pyzmq=27.1.0
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.14
  - wheel=0.45.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.9.1
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - anthropic==0.46.0
      - anyio==4.11.0
      - async-timeout==4.0.3
      - attrs==25.3.0
      - beautifulsoup4==4.14.2
      - brotli==1.1.0
      - cachetools==6.2.0
      - certifi==2025.8.3
      - cffi==2.0.0
      - cfgv==3.4.0
      - charset-normalizer==3.4.3
      - click==8.3.0
      - cobble==0.1.4
      - cssselect2==0.8.0
      - deprecated==1.3.1
      - distlib==0.4.0
      - distro==1.9.0
      - ebooklib==0.18
      - einops==0.8.1
      - et-xmlfile==2.0.0
      - fastapi==0.118.0
      - filelock==3.13.1
      - filetype==1.2.0
      - fonttools==4.60.1
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - google-ai-generativelanguage==0.6.15
      - google-api-core==2.28.1
      - google-api-python-client==2.187.0
      - google-auth==2.41.1
      - google-auth-httplib2==0.2.1
      - google-genai==1.39.1
      - google-generativeai==0.8.5
      - googleapis-common-protos==1.72.0
      - grpcio==1.76.0
      - grpcio-status==1.71.2
      - h11==0.16.0
      - httpcore==1.0.9
      - httplib2==0.31.0
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.35.3
      - identify==2.6.14
      - idna==3.10
      - img2pdf==0.6.1
      - jinja2==3.1.4
      - jiter==0.11.0
      - joblib==1.5.2
      - lxml==6.0.2
      - mammoth==1.11.0
      - markdown2==2.5.4
      - markdownify==1.2.0
      - marker-pdf==1.10.1
      - markupsafe==2.1.5
      - mpmath==1.3.0
      - multidict==6.6.4
      - networkx==3.3
      - nodeenv==1.9.1
      - numpy==2.1.2
      - openai==1.109.1
      - opencv-python-headless==4.11.0.86
      - openpyxl==3.1.5
      - pandas==2.3.3
      - pdf2image==1.17.0
      - pdftext==0.6.3
      - pikepdf==10.0.0
      - pillow==10.4.0
      - pre-commit==4.3.0
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==5.29.5
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.23
      - pycryptodome==3.23.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - pydantic-settings==2.11.0
      - pydyf==0.11.0
      - pymupdf==1.26.6
      - pyparsing==3.2.5
      - pypdf==6.2.0
      - pypdf2==3.0.1
      - pypdfium2==4.30.0
      - pyphen==0.17.2
      - python-dotenv==1.1.1
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - python-pptx==1.0.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - rapidfuzz==3.14.1
      - regex==2024.11.6
      - requests==2.32.5
      - rsa==4.9.1
      - safetensors==0.6.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - sniffio==1.3.1
      - soupsieve==2.8
      - starlette==0.48.0
      - surya-ocr==0.17.0
      - sympy==1.13.3
      - tenacity==9.1.2
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tinyhtml5==2.0.0
      - tokenizers==0.22.1
      - torch==2.8.0
      - torchvision==0.23.0
      - tqdm==4.67.1
      - transformers==4.56.2
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uritemplate==4.2.0
      - urllib3==2.5.0
      - uvicorn==0.37.0
      - virtualenv==20.34.0
      - watchfiles==1.1.0
      - weasyprint==63.1
      - webencodings==0.5.1
      - websockets==15.0.1
      - wrapt==2.0.0
      - xlsxwriter==3.2.9
      - yarl==1.20.1
      - zopfli==0.2.3.post1
